# Site settings
title: Rooha S
description: Personal portfolio website
# baseurl: "/portfolio" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rooha sulehri
user_description: I am a Computer Science graduate and over the past year, I have gained experience in using technologies like React.js and Redux, alongside basic understanding of Vue.js. I enjoy learning new things and being able to solve problems that are usually head scratchers, besides programming, I also have an interest in user experience, I believe I have a keen eye for detail and I use this skill to make strong design decisions when creating interfaces for users. Apart from learning new technologies and researching into them, I like to read books and create drawings in my spare time, I also enjoy playing board games because I am quite competitive and board games can be challenging. Furthermore, I go swimming once every week as it allows me to stay fit on days I am not working. 
user_title: User Interface Designer/Developer
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  rsulxo
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
